# Generated by Django 5.2.14 on 2026-06-23 09:58

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_item_upload_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('is_restricted', False), ('type', 'folder'), _connector='OR'), name='check_is_restricted_only_on_folders'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GistIndex(condition=models.Q(('is_restricted', True)), fields=['path'], name='drive_item_restricted_path_ix'),
        ),
    ]
